### ISSUE TITLE
Add cpp2wasm guide to examples

### ISSUE THREAD

**Issue by sverhoeven** [entangled/examples#1]
The [Guide to make C++ available as a web application](https://nlesc-jcer.github.io/cpp2wasm/) was written using entangled. It would be nice if it could be included in the list of examples.

**Comment by jhidding** [comment]
Do you have a nice image that could go as a thumbnail?

**Comment by jhidding** [comment]
I used the WASM logo for the moment

**Comment by sverhoeven** [comment]
Nice, thanks for including it.
